/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWorldsRouteImport } from './routes/app/worlds'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppWorldsIndexRouteImport } from './routes/app/worlds.index'
import { Route as AppWorldsCreateRouteImport } from './routes/app/worlds.create'
import { Route as AppStudioWorldIdRouteImport } from './routes/app/studio.$worldId'
import { Route as AppChatSessionIdRouteImport } from './routes/app/chat.$sessionId'
import { Route as AppWorldsWorldIdEditRouteImport } from './routes/app/worlds.$worldId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorldsRoute = AppWorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppWorldsIndexRoute = AppWorldsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorldsRoute,
} as any)
const AppWorldsCreateRoute = AppWorldsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppWorldsRoute,
} as any)
const AppStudioWorldIdRoute = AppStudioWorldIdRouteImport.update({
  id: '/studio/$worldId',
  path: '/studio/$worldId',
  getParentRoute: () => AppRoute,
} as any)
const AppChatSessionIdRoute = AppChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => AppRoute,
} as any)
const AppWorldsWorldIdEditRoute = AppWorldsWorldIdEditRouteImport.update({
  id: '/$worldId/edit',
  path: '/$worldId/edit',
  getParentRoute: () => AppWorldsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/worlds': typeof AppWorldsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/chat/$sessionId': typeof AppChatSessionIdRoute
  '/app/studio/$worldId': typeof AppStudioWorldIdRoute
  '/app/worlds/create': typeof AppWorldsCreateRoute
  '/app/worlds/': typeof AppWorldsIndexRoute
  '/app/worlds/$worldId/edit': typeof AppWorldsWorldIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/chat/$sessionId': typeof AppChatSessionIdRoute
  '/app/studio/$worldId': typeof AppStudioWorldIdRoute
  '/app/worlds/create': typeof AppWorldsCreateRoute
  '/app/worlds': typeof AppWorldsIndexRoute
  '/app/worlds/$worldId/edit': typeof AppWorldsWorldIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/worlds': typeof AppWorldsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/chat/$sessionId': typeof AppChatSessionIdRoute
  '/app/studio/$worldId': typeof AppStudioWorldIdRoute
  '/app/worlds/create': typeof AppWorldsCreateRoute
  '/app/worlds/': typeof AppWorldsIndexRoute
  '/app/worlds/$worldId/edit': typeof AppWorldsWorldIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/settings'
    | '/app/worlds'
    | '/app/'
    | '/app/chat/$sessionId'
    | '/app/studio/$worldId'
    | '/app/worlds/create'
    | '/app/worlds/'
    | '/app/worlds/$worldId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/settings'
    | '/app'
    | '/app/chat/$sessionId'
    | '/app/studio/$worldId'
    | '/app/worlds/create'
    | '/app/worlds'
    | '/app/worlds/$worldId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/settings'
    | '/app/worlds'
    | '/app/'
    | '/app/chat/$sessionId'
    | '/app/studio/$worldId'
    | '/app/worlds/create'
    | '/app/worlds/'
    | '/app/worlds/$worldId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/worlds': {
      id: '/app/worlds'
      path: '/worlds'
      fullPath: '/app/worlds'
      preLoaderRoute: typeof AppWorldsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/worlds/': {
      id: '/app/worlds/'
      path: '/'
      fullPath: '/app/worlds/'
      preLoaderRoute: typeof AppWorldsIndexRouteImport
      parentRoute: typeof AppWorldsRoute
    }
    '/app/worlds/create': {
      id: '/app/worlds/create'
      path: '/create'
      fullPath: '/app/worlds/create'
      preLoaderRoute: typeof AppWorldsCreateRouteImport
      parentRoute: typeof AppWorldsRoute
    }
    '/app/studio/$worldId': {
      id: '/app/studio/$worldId'
      path: '/studio/$worldId'
      fullPath: '/app/studio/$worldId'
      preLoaderRoute: typeof AppStudioWorldIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat/$sessionId': {
      id: '/app/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/app/chat/$sessionId'
      preLoaderRoute: typeof AppChatSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/worlds/$worldId/edit': {
      id: '/app/worlds/$worldId/edit'
      path: '/$worldId/edit'
      fullPath: '/app/worlds/$worldId/edit'
      preLoaderRoute: typeof AppWorldsWorldIdEditRouteImport
      parentRoute: typeof AppWorldsRoute
    }
  }
}

interface AppWorldsRouteChildren {
  AppWorldsCreateRoute: typeof AppWorldsCreateRoute
  AppWorldsIndexRoute: typeof AppWorldsIndexRoute
  AppWorldsWorldIdEditRoute: typeof AppWorldsWorldIdEditRoute
}

const AppWorldsRouteChildren: AppWorldsRouteChildren = {
  AppWorldsCreateRoute: AppWorldsCreateRoute,
  AppWorldsIndexRoute: AppWorldsIndexRoute,
  AppWorldsWorldIdEditRoute: AppWorldsWorldIdEditRoute,
}

const AppWorldsRouteWithChildren = AppWorldsRoute._addFileChildren(
  AppWorldsRouteChildren,
)

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppWorldsRoute: typeof AppWorldsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppChatSessionIdRoute: typeof AppChatSessionIdRoute
  AppStudioWorldIdRoute: typeof AppStudioWorldIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppWorldsRoute: AppWorldsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppChatSessionIdRoute: AppChatSessionIdRoute,
  AppStudioWorldIdRoute: AppStudioWorldIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
